name: Deploy Wijekoon Distributors Frontend to Droplet

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    name: Wijekoon Distributors QA Frontend Deployment
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH agent
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      # Test SSH connection
      - name: Test SSH Connection
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} "echo 'SSH connection successful!'"

      # Kill unnecessary user sessions
      - name: Kill unnecessary user sessions
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            current_user=$(whoami)
            current_pid=$$
            user_pids=$(ps -u $current_user -o pid=)

            for pid in $user_pids; do
              if [ "$pid" != "$current_pid" ]; then
                if ! ps -p $pid -o comm= | grep -E 'sshd|screen|tmux' > /dev/null; then
                  echo "Killing PID: $pid"
                  sudo kill -9 $pid || echo "Failed to kill PID: $pid"
                else
                  echo "Skipping PID: $pid (Necessary session)"
                fi
              fi
            done
          EOF

      # Build QA Frontend
      - name: Build Frontend
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use node
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"

            cd /var/www/qa/qa-wd-app

            if [ -d "dist" ]; then
              sudo rm -rf dist
              echo "Previous build deleted."
            fi

            npm cache clean --force
            echo "NPM cache cleaned."

            if [ ! -d "node_modules" ]; then
              npm install --production --legacy-peer-deps
            fi

            export NODE_OPTIONS="--max_old_space_size=512"
          
            git pull origin qa

            npm run lint
            npm install --force
            npm run build

            npm cache clean --force
          EOF

      # Start PM2 Prod Backend
      - name: Start PM2 Prod Backend
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use node
            cd /var/www/wijekoon-distributors/backend

            pm2 describe "wd-server" >/dev/null 2>&1 || pm2 start npm --name "wd-server" -- start
            pm2 restart "wd-server" --update-env
            pm2 save
          EOF

      # Start PM2 QA Backend
      - name: Start PM2 QA Backend
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use node
            cd /var/www/qa/wd-server-qa

            pm2 describe "wd-server-qa" >/dev/null 2>&1 || pm2 start npm --name "wd-server-qa" -- start
            pm2 restart "wd-server-qa" --update-env
            pm2 save
          EOF

      # Restart Nginx
      - name: Restart Nginx
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            sudo systemctl restart nginx.service
          EOF
