name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend to Droplet
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      # Test the connectivity
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} "echo 'SSH connection successful'"

      # Install dependencies and build
      - name: Build Frontend
        run: |
          npm ci
          npm run build

      # Deploy to droplet
      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            sudo rm -rf /var/www/wijekoon-distributors/frontend/*
            mkdir -p /var/www/wijekoon-distributors/frontend
          EOF
          
          scp -r dist/* ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:/var/www/wijekoon-distributors/frontend
          
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            sudo systemctl reload nginx
          EOF     
          
          # Reload Nginx
      - name: Reload Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            sudo systemctl reload nginx
          EOF
